### ISSUE TITLE
BOSH DNS causes CPU spikes in Windows 2016

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/dns-release#19] opened 2018-01-19 20:47 UTC
We deployed a windows 2016 vm with BOSH DNS enabled, and we noticed that every second the cpu would spike by about 30%.  
![cpu usage](https://user-images.githubusercontent.com/3689026/35170847-92a32584-fd2f-11e7-9138-210650a24af3.png)

On further investigation, we saw that the powershell that BOSH DNS brings up every second correlates to this spike in cpu. We can see the large cpu usage below.
![powershell](https://user-images.githubusercontent.com/3689026/35170894-bd93d6ee-fd2f-11e7-8033-a5f37f65dfea.png)

We think that one of [these commands](https://github.com/cloudfoundry/bosh-dns-release/blob/a7085d9096b78bbb6e3a6589814aab7060cdf84e/src/bosh-dns/dns/manager/windows_manager.go#L11-L60), along with spinning up a new powershell every second, is eating up the cpu on 2016 wndows machines.  

Thanks! 
Josh and @sunjayBhatia

**Comment by cppforlife** [comment] 2018-01-19 21:59
any ideas if shelling out on windows is so expensive? any suggestions from
bosh-agent world about what to do? load dll directly?

**Comment by sunjayBhatia** [comment] 2018-01-19 23:16
@cppforlife I think the `GetAdapterAddresses` function (Golang: https://godoc.org/golang.org/x/sys/windows#GetAdaptersAddresses, MSFT docs: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx is what you will want to take a look at first for the polling

It will give you a linked list of DNS server addresses (https://godoc.org/golang.org/x/sys/windows#IpAdapterDnsServerAdapter) for an adapter in this struct: https://godoc.org/golang.org/x/sys/windows#IpAdapterAddresses

**Comment by dpb587-pivotal** [comment] 2018-01-23 19:39
Story https://www.pivotaltracker.com/story/show/154493916

**Comment by cppforlife** [comment] 2018-01-23 19:39
story: https://www.pivotaltracker.com/story/show/154493916

**Comment by jrussett** [comment] 2018-01-26 00:56
@joshzarrabi, @sunjayBhatia, we tried reproducing this anomaly on stock Windows 2012r2 and 2016 server instances and saw nominal cpu utilization spikes when running the referenced resolver scripts. In both instances, the cpu would spike, but never pass 10% in the worst case.

Could you please provide us with the exact windows stemcell version where you saw this behavior, along with anything else unique about the instance that might have been impacting the performance (e.g. what kind of other jobs were installed and would they be manipulating network configuration during the dns configuration checks)?

**Comment by sesmith177** [comment] 2018-02-05 20:39
@jrussett @dpb587-pivotal we can reproduces this on a regular windows 2016 vm (so no BOSH or CF involved) just by running the `nameserverconfig.exe` process

@cppforlife starting a powershell process is expensive; but starting cmd.exe shell is not.

It looks like the `windowsManger.Read()` method could be implemented using the Go function @sunjayBhatia linked above. Since this method gets called every 3 seconds and since the `prepend-dns-server.ps1` script will not run must of the time, we think improving the `Read()` to not use powershell should resolve the problem

**Comment by cppforlife** [comment] 2018-02-15 19:51
fixed in https://github.com/cloudfoundry/bosh-dns-release/commit/4e39a0429d4fb89c5e30044c6490d30e94f17d19. coming version 1.2 will include this.

**Closed as completed by cppforlife** 2018-02-15 19:51 UTC
Labels: problem, planned-enhancement
