### ISSUE TITLE
bosh-dns-windows post-start script failed because of upcheck.bosh-dns timeout

### ISSUE THREAD

**Issue by lubronzhan** [cloudfoundry/dns-release#64] opened 2020-07-06 04:49 UTC
bosh-dns-windows post-start script failed.
```
Task 96 | 14:46:43 | Updating instance windows-worker: windows-worker/3a3835ae-fa86-4302-bee2-79b5b1f01b44 (1) (00:02:50)
                   L Error: Action Failed get_task: Task 866eb3c1-319e-46f5-74b0-34e3db31bc4a result: 1 of 3 post-start scripts failed. Failed Jobs: bosh-dns-windows. Successful Jobs: kubelet-windows, pks-nsx-t-dns-windows.
Task 96 | 14:49:33 | Error: Action Failed get_task: Task 866eb3c1-319e-46f5-74b0-34e3db31bc4a result: 1 of 3 post-start scripts failed. Failed Jobs: bosh-dns-windows. Successful Jobs: kubelet-windows, pks-nsx-t-dns-windows.
```
I checked the post-start error it’s because it timeout when doing Resolve-DnsName. 
```
upcheck.bosh-dns. : This operation returned because the timeout period expired
```

I manually run the post-start script and it works now, but according to the bosh-dns-windows log looks like it takes some time for it to get healthy:`(1:27)` , maybe this exceeded the timeout of command `Resolve-DnsName`
This is the log from `bosh-dns-windows/bosh-dns-healthcheck-windows/job-service-wrapper.out.log`
```
[Monitor] 2020/07/04 07:33:07 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:07 INFO - Status changed from running to failing
[Monitor] 2020/07/04 07:33:12 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:17 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:22 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:27 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:32 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:37 WARN - Agent reports unhealthy: {State:failing}
[Monitor] 2020/07/04 07:33:42 WARN - Agent reports unhealthy: {State:failing}
[healthcheck] 2020/07/04 07:34:30 INFO - Initializing
[healthcheck] 2020/07/04 07:34:30 INFO - Monitored jobs: [{HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[{Group:43 Name:kubernetes-workers Type:kubernetes-workers JobName:kubelet-windows}]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]} {HealthExecutablePath: Groups:[]}]
[Monitor] 2020/07/04 07:34:30 WARN - Agent reports unhealthy: {State:stopped}
[Monitor] 2020/07/04 07:34:30 INFO - Initial status: failing
[Monitor] 2020/07/04 07:34:35 INFO - Status changed from failing to running
```

Windows OS: `Windows Server 2019 Standard Evaluation   10.0.17763.1217`

Can we add retry around `Resolve-DnsName` https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns-windows/templates/post-start.ps1.erb#L19-L23?

Thank you

**Comment by hanlins** [comment] 2020-07-07 02:33
I think due to some ovs requirements, we need to reset the interface during `post-start` stage, see [here](https://gitlab.eng.vmware.com/PKS/pks-nsx-t-release/blob/feature/1.9/jobs/pks-nsx-t-dns-windows/templates/bin/post-start.ps1.erb#L16-26). That could be the cause of race condition. NCP team might have more context on justifying the needs of interface DNS client reset. It would be nice if can also add more retry logic here to make it more robust.

**Comment by hanlins** [comment] 2020-08-27 19:05
Hi Team, we saw this issue again in our pipeline:
```
upcheck.bosh-dns. : This operation returned because the timeout period expired
upcheck.bosh-dns. : This operation returned because the timeout period expired
upcheck.bosh-dns. : This operation returned because the timeout period expired
upcheck.bosh-dns. : This operation returned because the timeout period expired
upcheck.bosh-dns. : This operation returned because the timeout period expired
C:\var\vcap\jobs\bosh-dns-windows\bin\post-start.ps1 : tried to resolve five times but never succeeded
At line:1 char:1
+ \var\vcap\jobs\bosh-dns-windows\bin/post-start.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,post-start.ps1
```

Clearly retry is taking effect but it's not enough. I added timestamp in between each attempt and seems there's only 1 second between each retry so the tolerance is only 5 seconds:
```
PS C:\var\vcap\jobs\bosh-dns-windows\bin> vim .\post-start.ps1
PS C:\var\vcap\jobs\bosh-dns-windows\bin> .\post-start.ps1

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
------------                        --------- -------------                       ---------- -----       -------------- -------------
30.1.0.6                            53        0.0.0.0                             0          Listen                     1796
[08/27/2020 11:53:40] ### TIMESTAMP
upcheck.bosh-dns.xxx : DNS name does not exist
[08/27/2020 11:53:41] ### TIMESTAMP
upcheck.bosh-dns.xxx : DNS name does not exist
[08/27/2020 11:53:42] ### TIMESTAMP
upcheck.bosh-dns.xxx : DNS name does not exist
[08/27/2020 11:53:43] ### TIMESTAMP
upcheck.bosh-dns.xxx : DNS name does not exist
[08/27/2020 11:53:44] ### TIMESTAMP
upcheck.bosh-dns.xxx : DNS name does not exist
C:\var\vcap\jobs\bosh-dns-windows\bin\post-start.ps1 : tried to resolve five times but never succeeded
At line:1 char:1
+ .\post-start.ps1
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,post-start.ps1

```
I think we'd better extend the retry.

**Comment by lubronzhan** [comment] 2020-09-23 10:01
Hi team. We tested again by increasing the bosh-dns-windows timeout to 2 minutes in opsmanager advanced mode, Yu Yang can share her experiment result but the success rate is pretty high after the increase. So could we increase the timeout to 2 minutes?

**Comment by mrosecrance** [comment] 2020-10-16 17:26
Reopening since it seems like this issue is still happening. Which timeout did you change in opsman? I don't have access to your code base so I'm a little unclear on what you are doing. Is it a network reset done on a drain script? As part of your post-start? There's two relevant threads here: https://vmware.slack.com/archives/C3M0B3TV3/p1600455314012000?thread_ts=1600228199.163200&cid=C3M0B3TV3 and https://vmware.slack.com/archives/C3M0B3TV3/p1600228569165800 on this topic but I still don't understand what your flow is.

**Comment by mrosecrance** [comment] 2020-10-16 19:19
We did start this PR https://github.com/cloudfoundry/bosh-dns-release/pull/71 as I heard that Kevin provided a dev release for you to test, however once we get into minute plus timing ranges other things start to happen - like the bosh-agent will restart making task id's meaningless. At 10 minutes, we give up on the vm's entirely and resurrect them. Given that we've done a number of stories for adding timeouts only to find out that they need to be extended, I really want to understand more about what you are doing before continuing to just add time to all our counters.

**Comment by lubronzhan** [comment] 2020-10-23 03:24
Hi @mrosecrance, when staring the Windows VM, ~`ovs-windows` job will add HNSNetwork to Windows VM~ according to Hanlin said here https://github.com/cloudfoundry/bosh-dns-release/issues/64#issuecomment-654562228, it will reset interface, [code](https://gitlab.eng.vmware.com/PKS/pks-nsx-t-release/blob/feature/1.9/jobs/pks-nsx-t-dns-windows/templates/bin/post-start.ps1.erb#L16-26) , thus causing networking flake. This timeout varies, most of the time is 5s, but it could be longer due to unknown reasons, that's why we want to extend the bosh-dns post-start timeout.
Also during the draining of cluster, `ovs-windows` will delete the HNSNetwork, will also cause network flake, so the agent might restart during this period. 
Let me know if you need to know more about the steps
Thank you

**Comment by dlresende** [comment] 2020-11-06 15:45
Closing as #71 has been merged.

**Closed as completed by dlresende** 2020-11-06 15:45 UTC
