### ISSUE TITLE
Possible to provide APIs to CRUD bosh dns aliases?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#21] opened 2018-01-31 09:41 UTC
We have requirements to create new bosh dns aliases after the deployment is created. The current way is to add the aliases in the deployment manifest and run `bosh deploy` to update the whole deployment (thousands of vms) which is a big effort.
```
addons:
- name: dns
  jobs:
  - name: dns
    release: dns
    properties:
      aliases:
        a.bosh-dns-sl-cpi.bluemix.net: [169.10.10.88]
        b.bosh-dns-sl-cpi.bluemix.net: [169.10.10.99]     <-- new alias
```

Is it possible to provide APIs to create, retrieve, update and delete bosh dns aliases? In this way, bosh director can help synchronize the new bosh dns alias to all the vms just like the bosh native dns and no need to run `bosh deploy` to update the whole deployment.

/cc @mattcui

**Comment by gu-bin** [comment] 2018-02-01 02:06
@cppforlife Any comments?

/cc @mattcui

**Comment by cppforlife** [comment] 2018-02-01 03:42
bosh-dns by design does not concern itself with how data shows up on
different instances. for director internal data, director uses
agent/blobstore channel to sync its data.

one way to achieve syncing additional data (set of aliases) would be for you to make a custom job that
periodically downloads data from some source (your own source) and somehow
updates bosh-dns aliases. i think it would be possible to change bosh-dns
to automatically reload aliases, which leaves you with just figuring out
how to get the data on the vms. your data source could really be anything
from a blobstore, to another dns server, to something else.

does that sound reasonable?

**Comment by gu-bin** [comment] 2018-03-16 03:33
@cppforlife Yes, it's reasonable. Please change bosh-dns to automatically reload aliases.json. Thanks.

**Comment by andyliuliming** [comment] 2018-06-11 10:53
@gu-bin https://github.com/cloudfoundry/bosh-dns-release/pull/32 this PR makes auto-reload aliases.json hope @mfine30  can help merge.

**Comment by aashah** [comment] 2020-01-16 22:07
Hello,

In #32, there was a comment by Morgan sharing how custom data can be plugged into bosh-dns. Can I close this issue if that was an acceptable solution?

Best,
Aakash

**Comment by gu-bin** [comment] 2020-01-17 02:29
You can close this issue. Thanks.

**Closed as completed** 2020-01-17 05:36 UTC
