### ISSUE TITLE
Bosh DNS does not necessarily return all IP addresses for queries

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/dns-release#44] opened 2019-01-29 18:01 UTC
The query `dig @bosh-dns q-s4.*.bosh` documented [here](https://bosh.io/docs/dns/#constructing-queries) is not guaranteed to return all instances in large deployments: 

https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1547765338348400?thread_ts=1547753334.335800&cid=C02HPPYQ2

**Comment by aashah** [comment] 2019-04-03 18:35
Hey,

We'd like to hear your thoughts on actual and expected behavior.

* What are you seeing right now? Could you paste your dig results (censoring out any sensitive data)
* What data is being omitted? Are you aware of whether it is being truncated? Or do you suspect bosh-dns is omitting it?
* What do you expect to see?

Thanks,
Aakash & @jaresty

**Comment by luan** [comment] 2019-04-09 22:14
BOSH DNS implements the DNS protocol as per [ietf RFC 1035](https://www.ietf.org/rfc/rfc1035.txt).
Section 2.3.4. (Size limits) defines a maximum size for UDP messages to 512 octets (bytes) or less. So we truncate DNS response when working over UDP.

If you do you `dig` with the `+tcp` option you _should_ get the full un-truncated response.

I'm closing this based on the system working as intended. If you think there's an issue here that we didn't cover feel free to re-open.

Cheers!

**Closed as completed by luan** 2019-04-09 22:14 UTC
Labels: accepted
